### ISSUE TITLE
healeniumbackend Error

### ISSUE THREAD

**Issue by shiva4983** [healenium/healenium-backend#16]
Hi,

Getting the below error. When we run docker-compose on the latest update.

healenium_1 | 2020-11-23 23:25:06.003 WARN 1 - [ main] rvletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.ValidationFailedException: Validation Failed:\n 1 change sets check sum\n changelog/004_healingResult.xml::9::nkobzev was: 8:b916839b9918e0ec04ce87be4dfee7d2 but is now: 8:899edd768cc023ad1824af1eb759b375\n

healenium_1 | 2020-11-23 23:25:06.005 INFO 1 - [ main] c.z.hikari.HikariDataSource : HikariPool-1 - Shutdown initiated...

healenium_1 | 2020-11-23 23:25:06.018 INFO 1 - [ main] c.z.hikari.HikariDataSource : HikariPool-1 - Shutdown completed.

healenium_1 | 2020-11-23 23:25:06.024 INFO 1 - [ main] o.a.c.core.StandardService : Stopping service [Tomcat]

healenium_1 | 2020-11-23 23:25:06.071 INFO 1 - [ main] nEvaluationReportLoggingListener : \n \n Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.

healenium_1 | 2020-11-23 23:25:06.079 ERROR 1 - [ main] o.s.boot.SpringApplication : Application run failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.ValidationFailedException: Validation Failed:\n 1 change sets check sum\n changelog/004_healingResult.xml::9::nkobzev was: 8:b916839b9918e0ec04ce87be4dfee7d2 but is now: 8:899edd768cc023ad1824af1eb759b375\n \n at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1803)\n at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)\n at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)\n at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)\n at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)\n at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)\n at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)\n at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)\n at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)\n at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)\n at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)\n at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)\n at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)\n at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)\n at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)\n at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)\n at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)\n at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)\n at com.epam.healenium.Application.main(Application.java:9)\n at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n at java.lang.reflect.Method.invoke(Method.java:498)\n at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)\n at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)\n at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)\n at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)\n Caused by: liquibase.exception.ValidationFailedException: Validation Failed:\n 1 change sets check sum\n changelog/004_healingResult.xml::9::nkobzev was: 8:b916839b9918e0ec04ce87be4dfee7d2 but is now: 8:899edd768cc023ad1824af1eb759b375\n \n at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:291)\n at liquibase.Liquibase.update(Liquibase.java:198)\n at liquibase.Liquibase.update(Liquibase.java:179)\n at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:366)\n at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:314)\n at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)\n at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799)\n ... 26 common frames omitted\n

healeniumbackend_healenium_1 exited with code 1

**Comment by shiva4983** [comment]
After removing the db image and pulling it again resolved it.
