### ISSUE TITLE
unable to run latest backend , issue with s3 code , why amazonS3 is defaulted?

### ISSUE THREAD

**Issue by Zarkonan** [healenium/healenium-backend#39]
2021-08-08 06:05:34.558  INFO 14648 - [       main] o.a.c.core.StandardService       : Stopping service [Tomcat]
2021-08-08 06:05:34.575  INFO 14648 - [       main] nEvaluationReportLoggingListener : \n \n \n \n Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-08-08 06:05:34.582 ERROR 14648 - [       main] o.s.boot.SpringApplication       : Application run failed org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healingController' defined in URL [jar:file:/D:/dev/heal/healenium-backend/build/libs/hlm-backend-1.0-SNAPSHOT.jar!/BOOT-INF/classes!/com/epam/healenium/controller/HealingController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healingServiceImpl' defined in URL [jar:file:/D:/dev/heal/healenium-backend/build/libs/hlm-backend-1.0-SNAPSHOT.jar!/BOOT-INF/classes!/com/epam/healenium/service/impl/HealingServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 7; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'amazonS3ServiceImpl' defined in URL [jar:file:/D:/dev/heal/healenium-backend/build/libs/hlm-backend-1.0-SNAPSHOT.jar!/BOOT-INF/classes!/com/epam/healenium/service/impl/AmazonS3ServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amazonS3Repository': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amazonS3Client' defined in class path resource [com/epam/healenium/config/AmazonS3Configuration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.amazonaws.services.s3.AmazonS3]: Factory method 'amazonS3Client' threw exception; nested exception is java.lang.NullPointerException\n \n    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:787)\n \n      at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:226)\n \n      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)\n \n  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)\n \n        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)\n \n  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)\n \n         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)\n \n       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)\n \n      at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)\n \n        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)\n \n     at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)\n \n   at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)\n \n     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)\n \n  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)\n \n    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)\n \n       at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)\n \n   at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)\n \n   at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)\n \n     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)\n \n     at com.epam.healenium.Application.main(Application.java:9)\n \n      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n \n  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n \n        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n \n     at java.base/java.lang.reflect.Method.invoke(Method.java:567)\n \n      at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)\n \n       at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)\n \n       at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)\n \n       at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)\n \n Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healingServiceImpl' defined in URL [jar:file:/D:/dev/heal/healenium-backend/build/libs/hlm-backend-1.0-SNAPSHOT.jar!/BOOT-INF/classes!/com/epam/healenium/service/impl/HealingServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 7; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'amazonS3ServiceImpl' defined in URL [jar:file:/D:/dev/heal/healenium-backend/build/libs/hlm-backend-1.0-SNAPSHOT.jar!/BOOT-INF/classes!/com/epam/healenium/service/impl/AmazonS3ServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amazonS3Repository': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amazonS3Client' defined in class path resource [com/epam/healenium/config/AmazonS3Configuration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.amazonaws.services.s3.AmazonS3]: Factory method 'amazonS3Client' threw exception; nested exception is java.lang.NullPointerException\n \n      at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:787)\n \n         at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:226)\n \n      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)\n \n  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)\n \n        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)\n \n       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)\n \n    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)\n \n       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)\n \n      at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)\n \n        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)\n \n     at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)\n \n        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)\n \n  at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)\n \n         at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:874)\n \n         at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:778)\n \n         ... 27 common frames omitted\n \n Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'amazonS3ServiceImpl' defined in URL [jar:file:/D:/dev/heal/healenium-backend/build/libs/hlm-backend-1.0-SNAPSHOT.jar!/BOOT-INF/classes!/com/epam/healenium/service/impl/AmazonS3ServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amazonS3Repository': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amazonS3Client' defined in class path resource [com/epam/healenium/config/AmazonS3Configuration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.amazonaws.services.s3.AmazonS3]: Factory method 'amazonS3Client' threw exception; nested exception is java.lang.NullPointerException\n \n         at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:787)\n \n         at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:226)\n \n      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)\n \n  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)\n \n        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)\n \n       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)\n \n    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)\n \n       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)\n \n      at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)\n \n        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)\n \n     at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)\n \n        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)\n \n  at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)\n \n         at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:874)\n \n         at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:778)\n \n         ... 41 common frames omitted\n \n Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amazonS3Repository': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amazonS3Client' defined in class path resource [com/epam/healenium/config/AmazonS3Configuration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.amazonaws.services.s3.AmazonS3]: Factory method 'amazonS3Client' threw exception; nested exception is java.lang.NullPointerException\n \n  at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:337)\n \n   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1429)\n \n         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)\n \n       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)\n \n         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)\n \n  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)\n \n   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)\n \n   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)\n \n  at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)\n \n   at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)\n \n       at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)\n \n    at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:874)\n \n         at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:778)\n \n         ... 55 common frames omitted\n \n Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amazonS3Client' defined in class path resource [com/epam/healenium/config/AmazonS3Configuration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.amazonaws.services.s3.AmazonS3]: Factory method 'amazonS3Client' threw exception; nested exception is java.lang.NullPointerException\n \n      at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:645)\n \n         at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:475)\n \n    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)\n \n        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)\n \n        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)\n \n       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)\n \n    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)\n \n       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)\n \n      at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)\n \n        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)\n \n     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeanByName(AbstractAutowireCapableBeanFactory.java:454)\n \n  at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:543)\n \n        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:513)\n \n        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:653)\n \n     at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:224)\n \n       at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:116)\n \n    at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:334)\n \n   ... 67 common frames omitted\n \n Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.amazonaws.services.s3.AmazonS3]: Factory method 'amazonS3Client' threw exception; nested exception is java.lang.NullPointerException\n \n      at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)\n \n         at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:640)\n \n      ... 83 common frames omitted\n \n Caused by: java.lang.NullPointerException: null\n \n  at com.epam.healenium.util.Utils.getKeyFromKeyStore(Utils.java:53)\n \n         at com.epam.healenium.config.AmazonS3Configuration.amazonS3Client(AmazonS3Configuration.java:19)\n \n        at com.epam.healenium.config.AmazonS3Configuration$$EnhancerBySpringCGLIB$$77be4b9.CGLIB$amazonS3Client$0(<generated>)\n \n     at com.epam.healenium.config.AmazonS3Configuration$$EnhancerBySpringCGLIB$$77be4b9$$FastClassBySpringCGLIB$$69e7dd9d.invoke(<generated>)\n \n        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)\n \n   at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)\n \n       at com.epam.healenium.config.AmazonS3Configuration$$EnhancerBySpringCGLIB$$77be4b9.amazonS3Client(<generated>)\n \n  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n \n  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n \n        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n \n     at java.base/java.lang.reflect.Method.invoke(Method.java:567)\n \n      at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)\n \n      ... 84 common frames omitted\n \n

**Comment by Zarkonan** [comment]
i removed all reference to s3 and its working but i am not sure about the impact, also end up running pushgateway as well , which is not documented.

**Comment by Aliaksei-Ashukha** [comment]
It fixed at 3.1.2 version
