### ISSUE TITLE
BeanCreationException from Spring for a liquibase class

### ISSUE THREAD

**Issue by ddili** [healenium/healenium-backend#51]
Hello!

After upgrading to healenium/hlm-backend:3.2.0, we are getting a `BeanCreationException` from spring for a `liquibase` class and our Healenium container is unable to start.

Can someone please help us get this resolved? See below for the error and our docker-compose.yaml.

Thanks!

Error:
```
2022-02-10 16:30:27.114 ERROR 1 - [       main] o.s.boot.SpringApplication       : Application run failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.ValidationFailedException: Validation Failed:
      1 change sets check sum
           changelog/002_selector.xml::5::nkobzev was: 8:548308f3b8f4f0ead007c667a4a3d7bf but is now: 8:493ad322e36717cd9bf4488684f88288
 
         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1803)
         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
      at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
         at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)
       at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
       at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
       at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
       at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
      at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
       at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at com.epam.healenium.Application.main(Application.java:9)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
  at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
     at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
  at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
         at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
 Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
      1 change sets check sum
           changelog/002_selector.xml::5::nkobzev was: 8:548308f3b8f4f0ead007c667a4a3d7bf but is now: 8:493ad322e36717cd9bf4488684f88288
 
  at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:291)
         at liquibase.Liquibase.update(Liquibase.java:198)
    at liquibase.Liquibase.update(Liquibase.java:179)
     at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:366)
       at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:314)
         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)
       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799)
         ... 26 common frames omitted
```

docker-compose.yaml
```
services:

  db:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      - POSTGRES_DB=healenium
      - POSTGRES_USER=healenium_user
      - POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
    networks:
      - healenium

  healenium:
    image: healenium/hlm-backend:3.2.0
    ports:
      - "7878:7878"
    links:
      - db
    restart: always
    environment:
      - SPRING_CONTAINER_NAME=healenium
      - SPRING_POSTGRES_DB=healenium
      - SPRING_POSTGRES_USER=healenium_user
      - SPRING_POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
      - SPRING_POSTGRES_URL=jdbc:postgresql://db:5432/healenium?currentSchema=healenium
    networks:
      - healenium

  selector-imitator:
    image: healenium/hlm-selector-imitator:1
    restart: on-failure
    ports:
      - "8000:8000"

networks:
  healenium:
```

**Comment by ElenaStepuro** [comment]
Hello @ddili which healenium-web version do you use?

**Comment by ddili** [comment]
Hi @ElenaStepuro! Thanks for getting back to me! Sorry, I forgot to include some info in my original post.

We are using healenium-web 3.1.4
```
<dependency>
  <groupId>com.epam.healenium</groupId>
  <artifactId>healenium-web</artifactId>
  <version>3.1.4</version>
</dependency>
```

But the problem is occurring on container startup, not when we run our tests. Here is the output of `docker ps`. `infra_healenium_1` is stuck in a restarting loop with the same error from my original post.
```
CONTAINER ID   IMAGE                               COMMAND                  CREATED        STATUS                          PORTS                                       NAMES
05ba2efaa7d7   healenium/hlm-backend:3.2.0         "java -Djava.securit…"   2 days ago     Restarting (1) 14 seconds ago                                               infra_healenium_1
3c520abddcdc   postgres:11-alpine                  "docker-entrypoint.s…"   2 days ago     Up 25 hours                     0.0.0.0:5432->5432/tcp, :::5432->5432/tcp   infra_db_1
649a659bb36d   healenium/hlm-selector-imitator:1   "uvicorn app:app --h…"   4 months ago   Up 7 weeks                      0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   infra_selector-imitator_1
```

But perhaps I've missed something with my setup.

Thanks in advance for your help!

**Comment by ElenaStepuro** [comment]
Hello @ddili Please, update healenium-web version to 3.2.1
Version 3.1.4 is not compatible with back 3.2.0

**Comment by ddili** [comment]
Hi @ElenaStepuro, thanks for pointing that out! I've updated the healenium-web dependency to 3.2.1.

But when I do a `mvn clean compile` on our project there's an error from hlm-report-mvn. Any ideas? Note that I have masked sensitive information, like our IP address.
```
...
[INFO] --- hlm-report-mvn:1.1:initReport (hlmReport) @ test-project ---
[INFO] Healenium server Port = 7878
[INFO] Healenium server Host = dockerserver01
Feb 11, 2022 9:32:13 AM com.epam.healenium.client.HealingClient makePost
WARNING: Failed to perform POST request. Reason: Failed to connect to dockerserver01/<ip address>:7878
[INFO] sessionKey= null
[WARNING] Couldn't obtain session key from server!
...
```

Still, the healenium/hlm-backend:3.2.0 on our docker server isn't starting up. I believe that needs to be resolved before we can use healenium-web in our project.

And here's our hlm-report-mvn plugin configuration, in case there's something there we should also change.
```
<plugin>
	<groupId>com.epam.healenium</groupId>
	<artifactId>hlm-report-mvn</artifactId>
	<version>1.1</version>
	<executions>
		<execution>
			<id>hlmReport</id>
			<phase>compile</phase>
			<goals>
				<goal>initReport</goal>
			</goals>
		</execution>
		<execution>
			<id>hlmReportB</id>
			<phase>verify</phase>
			<goals>
				<goal>buildReport</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

Thanks again for your help!

**Comment by ElenaStepuro** [comment]
@ddili could you please, provide parameters from healenium.properties file?
As about plugin, did you set it up into <plugins> or into <pluginManagement>?

**Comment by ElenaStepuro** [comment]
Hello @ddili Oops! Sorry, some unexpected things during format...
I mean is it in **plugins** group or in **pluginManagement** group?

**Comment by ddili** [comment]
Hi @ElenaStepuro! Thanks for elaborating! It's in the `<plugins>` group.

But would you be able to explain why settings in our automation project are causing the BeanCreationException on our docker container? To me, them seem separate.

Thanks again!

**Comment by ElenaStepuro** [comment]
Hello @ddili.
As about report plugin, I've asked because you've specified it in report. Also in case if you're using pluginManagement, report will not be generated.

However, could you clarify did you add init.sql file into your project?

**Comment by ddili** [comment]
Hi @ElenaStepuro ! Sorry I didn't get back to you sooner today! Thanks for getting back to me!

We followed the https://github.com/healenium/healenium-backend#how-to-start guide to setup of our `/infra` directory on our docker server, which contains `init.sql`
```
user@dockerserver01:/infra$ tree
.
├── db
│   └── sql
│       └── init.sql
└── docker-compose.yaml

2 directories, 2 files
```
Here is the contents of `init.sql`
```
CREATE SCHEMA healenium AUTHORIZATION healenium_user;
GRANT USAGE ON SCHEMA healenium TO healenium_user;
```
Please note that our automation project and the docker container are running on **different** machines.

Let me know, and thanks again for your help!

**Comment by ElenaStepuro** [comment]
Hello @ddili I recommend to follow these steps:

1. kill all containers
2. instead of dockerserver01 use ip form
3. restart containers

**Comment by ddili** [comment]
Good day @ElenaStepuro! Thanks for getting back to me!

I was able to solve the problem after coming across issue https://github.com/healenium/healenium-backend/issues/19.

After stopping the containers, then updating this line in docker-compose.yaml
`- SPRING_POSTGRES_URL=jdbc:postgresql://db:5432/healenium?currentSchema=healenium`
to
`- SPRING_POSTGRES_URL=jdbc:postgresql://db:5432/healenium`
and then restarting docker-compose, `infra_healenium_1` is now up and running and the web client is working!

Thanks again @ElenaStepuro for your help! I am closing this issue.

Best regards!
