### ISSUE TITLE
[BUG]: Healenium is not healing broken locator in our applcation.

### ISSUE THREAD

**Issue by pramodmewada271219** [healenium/healenium-backend#60]
### Describe the bug

Error - java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.insurity.glp.automation.ui.core.system.BasePageUtil.pageAction(BasePageUtil.java:270)
	at com.insurity.glp.cxp.stepDefinition.StepDef.iFillDataOnThe(StepDef.java:139)
	at ✽.I fill data on the "Policy Manager"(file:///C:/Users/Pramod.Mewada/Desktop/cxp-ui-plugin/src/test/resources/features/test/ClaimProcess_Notepad_1.feature:16)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate WebElement {PolicyManager.SearchPolicyNumber_text}: @FindBy(css = input[id$='SearchPolicyNumber'])

	at org.openqa.selenium.support.pagefactory.AjaxElementLocator.findElement(AjaxElementLocator.java:99)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:39)
	at com.sun.proxy.$Proxy67.hashCode(Unknown Source)

Selenium version - 4

<dependency>
            <groupId>com.epam.healenium</groupId>
            <artifactId>healenium-web</artifactId>
            <version>3.2.3</version>
            <exclusions>
                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-java</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

if (healenabled.equalsIgnoreCase(PluginUtil.getInstance().getAppConfig().gethealenabled())) {
            driver = new HealingDriver().getInstance(driver);
            LOGGER.info("Using healenium driver..");
        }

![image](https://user-images.githubusercontent.com/113417431/189842833-663677b9-b40b-4ced-811c-da2abdf35523.png)

### How to reproduce the issue

```shell
None
```

### Logs appeared during using Healenium

```shell
None
```

### Healenium Web version

none

### Healenium Backend version

healenium/hlm-backend:3.2.2 

### Selenium version

4

### Platform

java

**Comment by Aliaksei-Ashukha** [comment]
Hi @pramodmewada271219 , Could you provide the whole stacktrace ?
